// 200 Thông Điệp Từ Vị Thần
// 50 thông điệp gốc + 150 thông điệp từ cuốn sách
const answers = [
    // ============================================
    // 50 THÔNG ĐIỆP GỐC (1-50)
    // ============================================

    // Về Tin Tưởng Bản Thân
    "Câu trả lời bạn tìm kiếm đã luôn tồn tại trong trái tim bạn. Hãy lắng nghe nó.",
    "Đừng nghi ngờ trực giác của mình. Nó là tiếng nói của linh hồn, dẫn lối bạn đi đúng đường.",
    "Bạn mạnh mẽ hơn bạn nghĩ, dũng cảm hơn bạn tin, và được yêu thương nhiều hơn bạn biết.",
    "Hãy tin vào bản thân như cách mặt trăng tin vào chu kỳ của mình - dù tối hay sáng, nó vẫn luôn trọn vẹn.",
    "Nỗi sợ hãi của bạn chỉ là bóng tối. Khi bạn tiến về phía trước, nó sẽ tự tan biến.",
    "Bạn không cần sự cho phép của ai để trở thành chính mình. Hãy tỏa sáng theo cách riêng của bạn.",
    "Hãy ngừng tìm kiếm sự hoàn hảo. Bạn đã đủ tốt đẹp trong chính khoảnh khắc này.",
    "Giọng nói bên trong bạn biết câu trả lời. Hãy cho nó không gian để được lắng nghe.",
    "Bạn là tác giả của câu chuyện đời mình. Đừng để người khác cầm bút thay bạn.",
    "Trong mỗi khoảnh khắc nghi ngờ, hãy nhớ rằng: Vũ trụ đã chọn bạn vì một lý do.",

    // Về Thay Đổi & Chuyển Hóa
    "Đây là thời điểm để thay đổi. Hãy buông bỏ những gì không còn phục vụ cho sự phát triển của bạn.",
    "Như con bướm rời khỏi kén, bạn phải trải qua bóng tối để tìm thấy đôi cánh của mình.",
    "Kết thúc chỉ là một khởi đầu được ngụy trang. Hãy đón nhận nó với vòng tay rộng mở.",
    "Bạn không cần phải biết toàn bộ con đường. Chỉ cần biết bước tiếp theo là đủ.",
    "Sự hỗn loạn bạn đang trải qua chính là sự sắp xếp lại của vũ trụ cho một điều tốt đẹp hơn.",
    "Hãy để phiên bản cũ của bạn ra đi. Phiên bản mới đang chờ được sinh ra.",
    "Mùa đông rồi sẽ qua, và mùa xuân sẽ đến. Hãy kiên nhẫn với chu kỳ của cuộc sống.",
    "Sự chuyển hóa đòi hỏi sự can đảm, nhưng phần thưởng sẽ xứng đáng với nỗi đau.",

    // Về Tình Yêu & Mối Quan Hệ
    "Tình yêu đang tìm đường đến với bạn. Hãy mở cửa trái tim.",
    "Hãy yêu thương bản thân trước. Đó là nền tảng cho mọi mối quan hệ khác.",
    "Người phù hợp sẽ xuất hiện khi bạn sẵn sàng, không phải khi bạn cô đơn.",
    "Hãy cho đi tình yêu mà không mong chờ. Vũ trụ sẽ trả lại cho bạn gấp bội.",
    "Hãy tha thứ - không phải vì họ xứng đáng, mà vì bạn xứng đáng được bình yên.",
    "Tình yêu thật sự không hoàn hảo, nhưng nó chân thật. Hãy trân trọng điều đó.",
    "Người bạn đang nghĩ đến cũng đang nghĩ về bạn. Hãy tin vào sự kết nối này.",

    // Về Công Việc & Sự Nghiệp
    "Đam mê của bạn là la bàn. Hãy theo đuổi điều khiến trái tim bạn cháy bỏng.",
    "Thành công không đến từ một đêm, mà từ hàng ngàn đêm kiên trì.",
    "Cơ hội đang gõ cửa. Hãy mở mắt và sẵn sàng đón nhận.",
    "Thất bại không phải là kết thúc - đó là bài học được ngụy trang.",
    "Đừng so sánh hành trình của bạn với người khác. Mỗi người có một con đường riêng.",
    "Hãy dám mơ lớn, nhưng bắt đầu từ những bước nhỏ. Mọi tòa nhà đều bắt đầu từ viên gạch đầu tiên.",
    "Sự sáng tạo của bạn là món quà. Đừng giấu nó đi mà hãy chia sẻ với thế giới.",
    "Hãy tin vào ý tưởng của mình. Nó có thể thay đổi cuộc sống của bạn và của nhiều người khác.",
    "Bạn được sinh ra để làm điều phi thường. Đừng bằng lòng với sự tầm thường.",

    // Về Thời Điểm & Sự Kiên Nhẫn
    "Vũ trụ có lịch trình riêng. Đừng cố ép buộc những gì chưa sẵn sàng.",
    "Hãy chờ đợi với niềm tin, không phải với sự lo lắng. Kết quả sẽ khác nhau hoàn toàn.",
    "Sự chậm trễ không phải là sự từ chối. Đôi khi nó là sự bảo vệ.",
    "Hạt giống đã được gieo. Hãy tưới nước và chờ đợi mùa thu hoạch.",
    "Bạn không muộn, bạn không sớm. Bạn đang đi đúng tiến độ của riêng mình.",
    "Bình minh đến sau những giờ tối nhất. Hãy giữ vững niềm tin.",

    // Về Sự Lựa Chọn
    "Hãy đi theo tiếng gọi của trái tim, dù nó có vẻ phi lý với logic.",
    "Cả hai lựa chọn đều dẫn đến sự phát triển. Hãy chọn con đường khiến bạn sợ hãi hơn một chút.",
    "Trực giác của bạn đã có câu trả lời. Đừng để nỗi sợ che mờ nó.",
    "Con đường ít người đi thường dẫn đến những điều phi thường nhất.",

    // Về Chữa Lành & Bình Yên
    "Hãy cho phép bản thân được chữa lành. Vết thương cũ không định nghĩa tương lai của bạn.",
    "Hãy buông bỏ những điều ngoài tầm kiểm soát. Năng lượng của bạn quý giá hơn thế.",
    "Thế giới bên ngoài là phản chiếu của thế giới bên trong. Hãy bắt đầu chữa lành từ bên trong.",
    "Hãy tha thứ cho bản thân về những sai lầm trong quá khứ. Bạn đã làm tốt nhất có thể với những gì bạn biết.",
    "Những gì bạn đang trải qua sẽ qua đi. Không có bão tố nào kéo dài mãi mãi.",
    "Hãy nhớ rằng: Mọi chuyện đều là tất nhiên, và bạn đang được bảo vệ trên hành trình này.",

    // ============================================
    // 150 THÔNG ĐIỆP TỪ CUỐN SÁCH (51-200)
    // ============================================

    "Có thể xảy ra.",
    "Hãy chờ đợi.",
    "Không phải lúc.",
    "Tập trung hơn.",
    "Kết quả tích cực.",
    "Nguy hiểm phía trước.",
    "Thời gian sẽ trả lời.",
    "Hãy thay đổi kế hoạch.",
    "Đúng hướng rồi.",
    "Không nên vội vàng.",
    "Vũ trụ ủng hộ.",
    "Cần thêm nỗ lực.",
    "Tránh xa lúc này.",
    "Cơ hội sắp đến.",
    "Hãy lắng nghe trực giác.",
    "Không chắc chắn.",
    "Bắt đầu ngay.",
    "Kiên nhẫn là chìa khóa.",
    "Kết thúc tốt đẹp.",
    "Xem xét lại.",
    "Có sự giúp đỡ.",
    "Đừng lo lắng.",
    "Hành động cần thiết.",
    "Tạm dừng đi.",
    "Sẽ ổn thôi.",
    "Tìm kiếm lời khuyên.",
    "Đường đi đúng.",
    "Cẩn thận chọn lựa.",
    "Thành công gần kề.",
    "Không thể lúc này.",
    "Tin vào bản thân.",
    "Thay đổi sắp tới.",
    "Hãy buông bỏ.",
    "Kết nối mạnh mẽ.",
    "Trì hoãn tốt hơn.",
    "Ngày mới sáng sủa.",
    "Tránh rủi ro.",
    "Ý tưởng hay đấy.",
    "Cần thời gian dài.",
    "Có lẽ vậy.",
    "Hãy tiến bước.",
    "Không đồng ý.",
    "Vũ trụ mách bảo.",
    "Giữ bình tĩnh.",
    "Cơ hội kép.",
    "Đừng ép buộc.",
    "Sẽ rõ ràng.",
    "Hành động ngay.",
    "Chờ tín hiệu.",
    "Tốt hơn mong đợi.",
    "Xem xét kỹ.",
    "Không đáng thử.",
    "Hỗ trợ đến.",
    "Thời điểm lý tưởng.",
    "Hãy linh hoạt.",
    "Kết quả trung bình.",
    "Tin tưởng quá trình.",
    "Tránh xung đột.",
    "Bắt đầu nhỏ.",
    "Sẽ thất bại.",
    "Tích cực lan tỏa.",
    "Cần nghỉ ngơi.",
    "Đúng người sai lúc.",
    "Hãy theo đuổi.",
    "Không hứa hẹn.",
    "Vũ trụ cười.",
    "Cải thiện dần.",
    "Đừng quay đầu.",
    "Bí mật hé lộ.",
    "Hãy tha thứ.",
    "Kết thúc chu kỳ.",
    "Bắt đầu mới.",
    "Cẩn trọng lời nói.",
    "Thành quả xứng đáng.",
    "Chờ đợi thêm.",
    "Ý tưởng tuyệt vời.",
    "Không phù hợp.",
    "Sức mạnh nội tại.",
    "Thời gian chữa lành.",
    "Hãy dũng cảm.",
    "Kết nối đứt đoạn.",
    "Tốt nhất hiện tại.",
    "Tránh xa hoàn toàn.",
    "Sẽ thành hiện thực.",
    "Giữ tâm trí mở.",
    "Không dễ dàng.",
    "Phần thưởng lớn.",
    "Hãy cân nhắc.",
    "Vũ trụ đồng hành.",
    "Kiên trì thắng lợi.",
    "Đừng mong đợi.",
    "Bước nhảy vọt.",
    "Cần sự giúp đỡ.",
    "Tất cả ổn định.",
    "Hãy buông tay.",
    "Cơ hội vàng.",
    "Không phải giờ.",
    "Tin vào phép màu.",
    "Kết thúc êm đẹp.",
    "Bắt đầu hành trình.",
    "Ánh sáng dẫn lối.",
    "Đừng kháng cự.",
    "Sóng gió qua nhanh.",
    "Hãy im lặng.",
    "Bí ẩn chờ khám phá.",
    "Không thể tránh.",
    "Tâm hồn biết đường.",
    "Thay đổi cần thiết.",
    "Kết quả bất ngờ.",
    "Giữ vững niềm tin.",
    "Thời cơ chín muồi.",
    "Tránh quyết định vội.",
    "Vũ trụ sắp xếp.",
    "Hành trình dài.",
    "Đúng thời điểm.",
    "Cần sự kiên định.",
    "Buông xả nhẹ nhàng.",
    "Cơ hội kép đôi.",
    "Không hối tiếc.",
    "Lắng nghe gió.",
    "Bước đi tự tin.",
    "Đừng sợ hãi.",
    "Kết nối sâu sắc.",
    "Tạm hoãn khôn ngoan.",
    "Sẽ tỏa sáng.",
    "Tìm bình yên.",
    "Đường cong uốn.",
    "Chọn lựa sáng suốt.",
    "Thành công lặng lẽ.",
    "Chưa sẵn sàng.",
    "Tin vào dòng chảy.",
    "Biến đổi tích cực.",
    "Hãy tha thứ.",
    "Sức mạnh nội tâm.",
    "Chờ đợi đáng giá.",
    "Ngày mai tươi sáng.",
    "Cảnh giác bóng tối.",
    "Ý tưởng rực rỡ.",
    "Thời gian dài hơn.",
    "Có lẽ không.",
    "Tiến tới mạnh mẽ.",
    "Phản đối nhẹ.",
    "Vũ trụ thì thầm.",
    "Bình an đến.",
    "Hai đường rẽ.",
    "Đừng gượng ép.",
    "Sẽ minh bạch.",
    "Hành động dứt khoát.",
    "Tín hiệu rõ ràng.",
    "Vượt mong đợi."
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = answers;
}
